name: rescale4dl
channels:
  - conda-forge
dependencies:
  - imageio=2.33.1
  - jupyter==1.1.1
  - matplotlib=3.9.2
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=23.3.1
  - pypdf=4.2.0
  - python=3.12.2
  - scikit-image=0.22.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - setuptools=68.2.2
  - tifffile=2024.12.12
  - pip:
        - nanopyx==1.0.0
