

name: Oncall Tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
                3.9
                3.10
                3.11
      - name: Run Nox Quick-Tests
        run: |
            python -m pip install --upgrade pip
            python -m pip install -e ".[all]"
            python -m pytest tests/*
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel }}


